"""One-time script to write Claude-generated descriptions for the 19 test layouts."""
import json
from pathlib import Path

OUT = Path(__file__).parent / "Planfinder_Dataset" / "pf_descriptions"

data = [
("L_L10.5_W12.0_de0_dp0.6_wp2",
 "1 double bedroom, 1 single bedroom, 1 full bathroom, 1 WC, open plan living-kitchen-dining, 1 storage room. Single-aspect apartment, windows on right facade. Kitchen at top-right corner of open plan space, wall counter along right wall, no kitchen island. Cook faces the wall, back to dining and living area. Kitchen is adjacent to the facade wall, well-lit cooking position. Living arrangement: split, seating area on left, dining and kitchen on right. Dining table visible, approximately 6 seats. TV visible on interior wall; diners do not face TV directly; cook cannot see TV. Bathroom config: 1 full bathroom; 1 WC-only room. Parallel morning routines possible. Both bedrooms accessed from corridor, no en-suite. Single bedroom large enough for bunk bed. Possible configurations for single bedroom: (1) children's bedroom; (2) home office or hobby room; (3) guest room; (4) bunk bed for two children. Storage room adjacent to kitchen zone, usable as kitchen pantry, laundry room or general storage. Entry from bottom via corridor. Door separates entry corridor from living area. Suits couples needing a spare room, people working from home.",
 ["en-suite requirement", "families with two or more children"],
 "2 bedroom, 2 bathroom, 1 living (open plan), 1 storage"),

("L_L10.5_W12.0_de0_dp0.9_wp0",
 "1 double bedroom, 1 single bedroom, 1 full bathroom, 1 WC, open plan living-kitchen-dining, 1 storage room. Single-aspect apartment, windows on left facade. Kitchen at top-left of open plan space, wall counter along left wall, no kitchen island. Kitchen adjacent to the facade wall, well-lit cooking position. Cook faces the wall, back to dining and living. Living arrangement: linear, kitchen left, dining center, seating area right. Dining table visible, approximately 6 seats. TV visible on right wall facing seating; cook cannot see TV. Bathroom config: 1 full bathroom; 1 WC-only room. Parallel morning routines possible. Both bedrooms accessed from corridor, no en-suite. Single bedroom large enough for bunk bed. Possible configurations: (1) children's bedroom; (2) home office or hobby room; (3) guest room; (4) bunk bed. Storage room adjacent to kitchen zone, usable as kitchen pantry, laundry or general storage. Entry from bottom near right side. Door separates entry corridor from living area. Suits couples needing a spare room, people working from home.",
 ["en-suite requirement", "families with two or more children"],
 "2 bedroom, 2 bathroom, 1 living (open plan), 1 storage"),

("L_L10.5_W12.0_de1_dp0.4_wp0",
 "1 double bedroom, 1 single bedroom, 1 full bathroom, 1 WC, open plan living-kitchen-dining, 1 storage room. Single-aspect apartment, windows on left facade. Kitchen at top-left corner of open plan space, L-shaped wall counter. Kitchen adjacent to the facade wall, well-lit cooking position. Cook faces the corner wall, back to dining and living. Living arrangement: L-shaped, kitchen in top-left corner, dining left-center, seating area bottom-left. Dining table visible, approximately 6 seats. No TV clearly visible. Bathroom config: 1 full bathroom; 1 WC-only room. Parallel morning routines possible. Both bedrooms on right side accessed from corridor. No en-suite. Single bedroom large enough for bunk bed. Possible configurations: (1) children's bedroom; (2) home office or hobby room; (3) guest room; (4) bunk bed. Storage room adjacent to kitchen zone, usable as kitchen pantry, laundry or general storage. Entry from right. Door separates entry corridor from living area. Suits couples needing a spare room, people working from home.",
 ["en-suite requirement", "families with two or more children"],
 "2 bedroom, 2 bathroom, 1 living (open plan), 1 storage"),

("L_L10.5_W12.0_de1_dp0.7_wp4",
 "1 double bedroom, 1 single bedroom, 1 full bathroom, 1 WC, open plan living-kitchen-dining, 1 storage room. Double-aspect apartment, windows on two facades. Kitchen at bottom-right of open plan space, wall counter, no kitchen island. Cook faces the wall, back to dining and seating. Living arrangement: split, seating bottom-left, dining bottom-center, kitchen bottom-right. Dining table visible, approximately 6 seats. No TV clearly visible. Bathroom config: 1 full bathroom; 1 WC-only room. Parallel morning routines possible. Large double bedroom (23.2sqm) at top-left. Single bedroom (16.5sqm) accessed from corridor. No en-suite. Single bedroom large enough for bunk bed. Possible configurations: (1) children's bedroom; (2) home office or hobby room; (3) guest room; (4) bunk bed. Storage room adjacent to kitchen zone, usable as kitchen pantry, laundry or general storage. Entry from right. Door separates entry corridor from living area. Suits couples needing a spare room, people working from home.",
 ["en-suite requirement", "families with two or more children"],
 "2 bedroom, 2 bathroom, 1 living (open plan), 1 storage"),

("L_L10.5_W12.0_de1_dp0.8_wp1",
 "1 double bedroom, 1 single bedroom, 1 full bathroom, 1 WC, open plan living-kitchen-dining, 1 storage room. Single-aspect apartment, windows on bottom facade. Kitchen at bottom of open plan space, wall counter, no kitchen island. Kitchen adjacent to the bottom facade wall, well-lit cooking position. Cook faces the bottom wall, back to dining and seating. Living arrangement: linear top-to-bottom, seating at top, coffee table center, dining lower, kitchen at bottom. Dining table visible, approximately 6 seats. No TV clearly visible. Bathroom config: 1 full bathroom; 1 WC-only room. Parallel morning routines possible. Both bedrooms on right side accessed from corridor. No en-suite. Single bedroom large enough for bunk bed. Possible configurations: (1) children's bedroom; (2) home office or hobby room; (3) guest room; (4) bunk bed. Storage room adjacent to kitchen zone, usable as kitchen pantry, laundry or general storage. Entry from right near bottom of wall. Door separates entry corridor from living area. Suits couples needing a spare room, people working from home.",
 ["en-suite requirement", "families with two or more children"],
 "2 bedroom, 2 bathroom, 1 living (open plan), 1 storage"),

("L_L10.5_W12.0_de2_dp0.5_wp4",
 "1 master suite (en-suite bathroom), 1 single bedroom, 1 shared full bathroom, open plan living-kitchen-dining, 1 storage room. Double-aspect apartment, windows on two facades. En-suite bathroom (4.5sqm) directly accessible from master bedroom. Kitchen in lower section of open plan space, wall counter, no kitchen island. Cook faces wall. Living arrangement: large L-shaped open plan, kitchen at one end, dining table center, seating extending into right wing. Dining table visible, approximately 6 seats. TV visible in living area. Bathroom config: 1 en-suite bathroom accessible from master bedroom only; 1 shared full bathroom from corridor. Single bedroom has desk visible in plan. Large enough for bunk bed. Possible configurations: (1) children's bedroom; (2) home office or hobby room; (3) guest room; (4) bunk bed. Storage room adjacent to kitchen zone, usable as kitchen pantry, laundry or general storage. Entry from top. Door separates entry corridor from living area. Suits couples with occasional guest, people working from home in single bedroom.",
 ["families requiring two children's bedrooms and a home office simultaneously"],
 "2 bedroom, 2 bathroom, 1 living (open plan), 1 storage"),

("L_L10.5_W12.0_de2_dp0.8_wp2",
 "1 double bedroom, 1 single bedroom, 1 full bathroom, 1 WC, open plan living-kitchen-dining, 1 storage room. Single-aspect apartment, windows on right facade. Kitchen at right side of open plan space, wall counter along right wall, no kitchen island. Kitchen adjacent to facade wall, well-lit cooking position. Cook faces the wall, back to dining and seating. Living arrangement: split, seating left, dining center, kitchen right. Dining table visible, approximately 6 seats. No TV clearly visible. Bathroom config: 1 full bathroom; 1 WC-only room. Parallel morning routines possible. Both bedrooms at top accessed from corridor. No en-suite. Single bedroom large enough for bunk bed. Possible configurations: (1) children's bedroom; (2) home office or hobby room; (3) guest room; (4) bunk bed. Storage room adjacent to kitchen zone, usable as kitchen pantry, laundry or general storage. Entry from top. Door separates entry corridor from living area. Suits couples needing a spare room, people working from home.",
 ["en-suite requirement", "families with two or more children"],
 "2 bedroom, 2 bathroom, 1 living (open plan), 1 storage"),

("L_L10.5_W12.0_de2_dp0.8_wp4",
 "1 double bedroom, 1 single bedroom, 1 full bathroom, 1 WC, open plan living-kitchen-dining, 1 storage room. Double-aspect apartment, windows on two facades. Kitchen at bottom-right of open plan space, wall counter, no kitchen island. Cook faces the wall, back to dining and seating. Living arrangement: split, seating bottom-left, dining bottom-center, kitchen bottom-right. Dining table visible, approximately 6 seats. No TV clearly visible. Bathroom config: 1 full bathroom; 1 WC-only room. Parallel morning routines possible. Large double bedroom at top-left. Single bedroom accessed from corridor. No en-suite. Single bedroom large enough for bunk bed. Possible configurations: (1) children's bedroom; (2) home office or hobby room; (3) guest room; (4) bunk bed. Storage room adjacent to kitchen zone, usable as kitchen pantry, laundry or general storage. Entry from top. Door separates entry corridor from living area. Suits couples needing a spare room, people working from home.",
 ["en-suite requirement", "families with two or more children"],
 "2 bedroom, 2 bathroom, 1 living (open plan), 1 storage"),

("L_L10.5_W12.0_de3_dp0.4_wp0",
 "1 double bedroom, 1 single bedroom, 1 full bathroom, 1 WC, open plan living-kitchen-dining, 1 storage room. Single-aspect apartment, windows on right facade. Kitchen at top-right of open plan space, wall counter, no kitchen island. Kitchen adjacent to right facade, well-lit cooking position. Cook faces the wall, back to dining and living. Living arrangement: vertical, kitchen at top-right, dining center, seating at bottom. Dining table visible, approximately 6 seats. No TV clearly visible. Bathroom config: 1 full bathroom; 1 WC-only room. Parallel morning routines possible. Both bedrooms on left side accessed from corridor. No en-suite. Single bedroom large enough for bunk bed. Possible configurations: (1) children's bedroom; (2) home office or hobby room; (3) guest room; (4) bunk bed. Storage room adjacent to kitchen zone, usable as kitchen pantry, laundry or general storage. Entry from left. Door separates entry corridor from living area. Suits couples needing a spare room, people working from home.",
 ["en-suite requirement", "families with two or more children"],
 "2 bedroom, 2 bathroom, 1 living (open plan), 1 storage"),

("L_L10.5_W12.0_de3_dp0.8_wp4",
 "1 master suite (en-suite bathroom with bathtub), 1 single bedroom, 1 shower bathroom, 1 WC, open plan living-kitchen-dining, 1 storage room. Double-aspect apartment, windows on two facades. Three separate wet rooms: en-suite bathroom with bathtub (11.9sqm) accessible only from master bedroom; shower bathroom (6.4sqm) from corridor; WC (2.5sqm) from corridor. Fully parallel morning routines possible for a household of three or more. Kitchen in open plan space, wall counter, no kitchen island. Cook faces wall. Living area with dining and seating zone. Dining table visible, approximately 6 seats. Bathroom config: 1 en-suite with bathtub; 1 shower-only bathroom; 1 WC. Master bedroom accessed via corridor with good acoustic separation. Single bedroom (9sqm) large enough for bunk bed. Possible configurations: (1) children's bedroom; (2) home office or hobby room; (3) guest room; (4) bunk bed. Storage room in corridor zone, suitable for coats, bikes, laundry or utility storage. Entry from left. Door separates entry corridor from living area. Suits couples or small families where morning routine convenience is a priority.",
 ["households requiring two separate children's bedrooms and a home office simultaneously"],
 "2 bedroom, 3 bathroom, 1 living (open plan), 1 storage"),

("L_L10.5_W13.5_de2_dp0.5_wp5",
 "1 double bedroom, 2 single bedrooms, 1 full bathroom with bathtub and shower, 1 WC, open plan living-kitchen-dining, 1 storage room. Double-aspect apartment, windows on two facades. Kitchen island present, hob on island facing dining table and living area. Cook at island faces the room, suited to cooking while entertaining or supervising children. Wall counter provides additional storage and workspace. Living arrangement: split, seating area on left, kitchen island and dining on right. Dining table visible, approximately 6 seats. Bathroom config: 1 full bathroom with bathtub and shower; 1 WC-only room. Parallel morning routines possible. Double bedroom (15.4sqm) and 2 single bedrooms (14.5sqm and 11.5sqm) all from central corridor, no en-suite. 1 of 2 single bedrooms has a desk visible. Both large enough for bunk bed. Possible configurations, mutually exclusive: (1) two children's bedrooms; (2) one children's bedroom and one home office; (3) two home offices; (4) one or both as guest rooms; (5) bunk bed in one or both. Cannot simultaneously provide two children's bedrooms and a home office without bunk bed. Storage room in corridor zone, suitable for coats, bikes, laundry or utility storage, not adjacent to kitchen. Entry from top. Door separates entry corridor from living area. Suits families with one or two children, households working from home, people who cook while entertaining.",
 ["en-suite requirement", "two children's bedrooms and home office simultaneously without bunk bed"],
 "3 bedroom, 2 bathroom, 1 living (open plan), 1 storage"),

("L_L10.5_W15.0_de0_dp0.2_wp3",
 "1 double bedroom, 1 single bedroom, 1 full bathroom, 1 WC, open plan living-kitchen-dining, 1 storage room. Double-aspect apartment, windows on left and right facades. Kitchen at top-left of open plan space, wall counter, no kitchen island. Kitchen adjacent to left facade, well-lit cooking position. Cook faces wall, back to dining and seating. Living arrangement: kitchen top-left, dining top-center, seating top-right. Dining table visible, approximately 6 seats. TV visible in seating area. Bathroom config: 1 full bathroom; 1 WC-only room. Parallel morning routines possible. Both bedrooms in lower private zone from corridor. No en-suite. Large corridor (14.5sqm) provides generous circulation. Single bedroom large enough for bunk bed. Possible configurations: (1) children's bedroom; (2) home office or hobby room; (3) guest room; (4) bunk bed. Storage room in corridor zone, suitable for coats, bikes, laundry or utility storage. Entry from bottom near left side. Door separates entry corridor from living area. Suits couples needing a spare room, people working from home.",
 ["en-suite requirement", "families with two or more children"],
 "2 bedroom, 2 bathroom, 1 living (open plan), 1 storage"),

("L_L10.5_W15.0_de0_dp0.3_wp3",
 "1 double bedroom, 1 single bedroom, 1 full bathroom, 1 WC, open plan living-kitchen-dining, 1 storage room. Double-aspect apartment, windows on left and right facades. Kitchen at top-left of open plan space, wall counter, no kitchen island. Kitchen adjacent to left facade, well-lit cooking position. Cook faces wall, back to dining and seating. Living arrangement: kitchen top-left, dining top-center, seating top-right. Dining table visible, approximately 6 seats. TV visible in seating area. Bathroom config: 1 full bathroom; 1 WC-only room. Parallel morning routines possible. Both bedrooms in lower private zone from corridor. No en-suite. Large corridor (14.5sqm) provides generous circulation. Single bedroom large enough for bunk bed. Possible configurations: (1) children's bedroom; (2) home office or hobby room; (3) guest room; (4) bunk bed. Storage room in corridor zone, suitable for coats, bikes, laundry or utility storage. Entry from bottom. Door separates entry corridor from living area. Suits couples needing a spare room, people working from home.",
 ["en-suite requirement", "families with two or more children"],
 "2 bedroom, 2 bathroom, 1 living (open plan), 1 storage"),

("L_L10.5_W15.0_de0_dp0.6_wp5",
 "1 double bedroom, 1 single bedroom, 1 full bathroom, 1 WC, open plan living-kitchen-dining, 1 storage room. Double-aspect apartment, windows on two facades including top facade, providing additional natural light into the living area. Kitchen at top area of open plan space, wall counter, no kitchen island. Cook faces wall, back to dining area. Living arrangement: dining top-left, kitchen top-right, seating center. Dining table visible, approximately 6 seats. Bathroom config: 1 full bathroom; 1 WC-only room. Parallel morning routines possible. Both bedrooms in lower private zone from corridor. No en-suite. Single bedroom large enough for bunk bed. Possible configurations: (1) children's bedroom; (2) home office or hobby room; (3) guest room; (4) bunk bed. Storage room in corridor zone, suitable for coats, bikes, laundry or utility storage. Entry from bottom. Door separates entry corridor from living area. Suits couples needing a spare room, people working from home.",
 ["en-suite requirement", "families with two or more children"],
 "2 bedroom, 2 bathroom, 1 living (open plan), 1 storage"),

("L_L10.5_W15.0_de1_dp0.3_wp3",
 "1 master suite (en-suite bathroom), 2 single bedrooms, 1 shared full bathroom, 1 WC, open plan living-kitchen-dining, 1 storage room. Double-aspect apartment, windows on two facades. En-suite bathroom (9.4sqm) directly accessible from master bedroom. Kitchen at bottom-left of open plan space, wall counter, no kitchen island. Cook faces wall, back to seating area. Living arrangement: seating top-left, dining bottom-left, kitchen bottom-center. Dining table visible, approximately 6 seats. TV visible in seating area. Bathroom config: 1 en-suite bathroom; 1 shared full bathroom; 1 WC. Good parallel morning routine capacity, en-suite serves master, shared bathroom and WC serve rest of household. 2 single bedrooms (14.6sqm and 13.8sqm) from corridor, both large enough for bunk bed. Possible configurations, mutually exclusive: (1) two children's bedrooms; (2) one children's bedroom and one home office; (3) two home offices; (4) one or both as guest rooms; (5) bunk bed arrangement. Cannot simultaneously provide two children's bedrooms and a home office without bunk bed. Storage room in corridor zone, suitable for coats, bikes, laundry or utility storage. Entry from right. Door separates entry corridor from living area. Suits families with one or two children, households working from home.",
 ["two children's bedrooms and a home office simultaneously without bunk bed"],
 "3 bedroom, 3 bathroom, 1 living (open plan), 1 storage"),

("L_L10.5_W15.0_de1_dp0.4_wp5",
 "1 master suite (en-suite bathroom), 2 single bedrooms, 1 shared full bathroom, open plan living-kitchen-dining, 1 storage room. Double-aspect apartment, windows on two facades. En-suite bathroom (10.3sqm) directly accessible from very large master bedroom (28.4sqm). Kitchen at top of open plan space, wall counter, no kitchen island. Cook faces wall, back to dining area. Living arrangement: dining top-center, kitchen top-right, seating top-left. Dining table visible, approximately 6 seats. Bathroom config: 1 en-suite bathroom (10.3sqm); 1 shared full bathroom (5.9sqm). No separate WC. 2 single bedrooms (16sqm and 15.4sqm) both large enough for bunk bed. No door between living area and private zone, open flow throughout apartment. Possible configurations, mutually exclusive: (1) two children's bedrooms; (2) one children's bedroom and one home office; (3) two home offices; (4) one or both as guest rooms; (5) bunk bed arrangement. Storage room in entry zone, suitable for coats, bikes, laundry or utility storage. Entry from right. Suits families with one or two children, households prioritising a large master bedroom.",
 ["two children's bedrooms and home office simultaneously without bunk bed", "household requiring acoustic separation between living and private zone"],
 "3 bedroom, 2 bathroom, 1 living (open plan), 1 storage"),

("L_L10.5_W16.5_de0_dp0.85_wp3",
 "1 double bedroom, 1 single bedroom, 1 full bathroom, 1 WC, open plan living-kitchen-dining, 1 large storage room. Corner-aspect apartment, windows on four facades, exceptional natural light throughout. Kitchen island present, hob on island facing dining table and living area. Cook at island faces the room, suited to cooking while entertaining or supervising children. Wall counter on left side provides additional workspace and storage. Very large open plan space (70.6sqm) with generous dining, seating and kitchen zones. Living arrangement: wall counter and kitchen island on left, dining to the right of island, large seating area on far right. Dining table visible, approximately 6 seats. Bathroom config: 1 full bathroom (9.3sqm); 1 WC-only room (2sqm). Parallel morning routines possible. Both bedrooms in lower private zone (21.6sqm and 19.1sqm), no en-suite. Very large storage room (25.6sqm), suitable as walk-in wardrobe, home gym, laundry or hobby space. Entry from bottom near right side. Door separates entry corridor from living area. Suits couples who entertain frequently, households prioritising large living space and abundant storage.",
 ["en-suite requirement", "families with two or more children needing multiple bedrooms"],
 "2 bedroom, 2 bathroom, 1 living (open plan), 1 large storage"),

("L_L10.5_W6.0_de1_dp0.5_wp5",
 "1 double bedroom, 1 full bathroom with bathtub, 1 small storage room, open plan living-kitchen-dining. Double-aspect apartment, windows on two facades. Compact layout. Kitchen at bottom-left of living area, wall counter, hob visible, no kitchen island. Kitchen adjacent to left facade window, well-lit cooking position. Cook faces the wall. Living area combines seating, compact dining and kitchen in one open space. Circular dining table visible, seating for approximately 2 to 4 people. Bathroom (7.1sqm) accessible from corridor, generous size with bathtub visible in plan. No separate WC, single bathroom serves the whole household. No corridor door separating living and bedroom zones, open flow throughout. Bedroom (12.1sqm) with double bed at far end from entry. Small storage room (5.3sqm) near entry, suitable for coats and shoes. Entry from right. Suits single person or couple.",
 ["families with children", "more than two occupants", "household requiring separate WC and shower"],
 "1 bedroom, 1 bathroom, 1 living (open plan), 1 storage"),

("L_L9.0_W16.5_de3_dp0.3_wp3",
 "1 master suite (en-suite bathroom with bathtub, walk-in wardrobe), 2 single bedrooms, 1 shared bathroom, open plan living-kitchen-dining, 1 storage room. Double-aspect apartment, windows on right and bottom facades. All three bedrooms face the full-height right facade. Living area faces the bottom facade. Kitchen island present, hob on island facing dining table and living area. Wall countertop runs along the full width of the room allowing for abundant full-height cabinet storage and large appliances. Cook at island directly faces the dining and seating area, suited to cooking while entertaining or supervising children. Living arrangement: linear, kitchen island and wall counter on left, dining center, seating on right. Dining table visible, approximately 6 seats. TV visible in living area facing seating; cook cannot see TV from island; diners face TV. En-suite bathroom (9.8sqm) with bathtub accessible only from master bedroom (27sqm). Walk-in wardrobe in master bedroom, open wardrobe area with two facing storage units, no closing door. Shared bathroom (5.7sqm) from corridor. Both single bedrooms (15.2sqm and 14.7sqm) have desk visible. Each large enough for bunk bed. Possible configurations, mutually exclusive: (1) two children's bedrooms; (2) one children's bedroom and one home office; (3) two home offices; (4) one or both as guest rooms; (5) bunk bed arrangement. Cannot simultaneously provide two children's bedrooms and a home office without bunk bed. Storage room near entry, suitable for coats, shoes, bikes or utility storage. Entry area provides space for coat and shoe storage. No door between entry and kitchen, relevant where local regulations require separation. Master suite at far end from living area, maximum acoustic separation. Suits families with one or two children, couples working from home, households prioritising communal cooking and dining.",
 ["closed kitchen preference", "two children's bedrooms and home office simultaneously without bunk bed", "jurisdictions requiring door separation between entry and kitchen"],
 "3 bedroom, 2 bathroom, 1 living (open plan), 1 storage")
]

for lid, desc, not_suit, summary in data:
    out = OUT / f"{lid}.json"
    obj = {"layoutId": lid, "description": desc, "not_suitable_for": not_suit, "rooms_summary": summary}
    out.write_text(json.dumps(obj, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"saved {lid}")

print(f"\nDone: {len(data)} files written")
